DROP TABLE MINIBUS;

CREATE TABLE MINIBUS
(
    NOMINIBUS INT PRIMARY KEY NOT NULL,
    CAPACITE INT
);

INSERT INTO MINIBUS (NOMINIBUS,CAPACITE) VALUES (1, 5) ;

INSERT INTO MINIBUS (NOMINIBUS,CAPACITE) VALUES (2, 8);
    
INSERT INTO MINIBUS (NOMINIBUS,CAPACITE) VALUES (3, 13);

INSERT INTO MINIBUS (NOMINIBUS,CAPACITE) VALUES (4, 4);
